"use client";

import { useState } from "react";
import { AdapterDayjs } from "@mui/x-date-pickers/AdapterDayjs";
import { QueryClient, QueryClientProvider } from "react-query";
import { LocalizationProvider } from "@mui/x-date-pickers";
// Collects CSS generated by MUI, which is streamed by Next.js to client
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import ContextProvider from "./context/ContextProvider";
import CustomThemeProvider from "@/styles/ThemeProvider";
import { useTheme, ThemeProvider, CssBaseline } from "@mui/material";
import theme from "@/styles/theme";

// Code from https://www.youtube.com/watch?v=9kjc6SWxBIA
export default function Providers({ children }) {
    // const theme = useTheme();

    const themeFunc = () => theme('light');

    const [queryClient] = useState(
        () =>
            new QueryClient({
                defaultOptions: {
                    queries: {
                        staleTime: 6 * 1000,
                        refetchInterval: 6 * 1000,
                        retry: false
                    },
                    // Credit: config from  https://github.com/TkDodo/testing-react-query/blob/main/src/tests/utils.tsx
                    logger: {
                        log: console.log,
                        warn: console.warn,
                        error: () => {}
                    }
                },
            })
    );

    

    return (
        <AppRouterCacheProvider>
            <CustomThemeProvider>
            {/* <ThemeProvider theme={themeFunc}> */}
                <CssBaseline />
                <LocalizationProvider dateAdapter={AdapterDayjs}>
                    <QueryClientProvider client={queryClient}>
                        <ContextProvider>
                            {children}
                        </ContextProvider>
            {/* <ThemeProvider theme={theme}>
                <QueryClientProvider client={queryClient}>
                    {children}
                </QueryClientProvider>
            </ThemeProvider> */}
                    </QueryClientProvider>
                </LocalizationProvider>
            </CustomThemeProvider>
            {/* </ThemeProvider> */}
        </AppRouterCacheProvider>
    );
}
